on: [push]

jobs:
  test:
    name: Build binary
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21' # The Go version to download (if necessary) and use.
      - name: Build file
        run: GOOS=linux GOARCH=amd64 go build -o fog && zip unstable.zip fog
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::613864977396:role/github-oidc-FogS3DeploymentsRole-EQO45UDOAHSL
          aws-region: us-east-1
      - name: Copy to S3 bucket
        run: aws s3 cp unstable.zip s3://public.ig.nore.me/fog/unstable.zip